### ISSUE TITLE
.NET core version

### ISSUE THREAD

**Issue by dotnetshadow** [jamesej/lynicon#1]
This project looks interesting I was wondering when a .net core version might be available?

**Comment by jamesej** [comment]
Hi

Thanks for your interest. The .Net Core version is currently in testing, hopefully it might be released in around a month or so.
Do let me know how to contact you to let you know when this happens if you would like to be notified.

If you have any other questions, don't hesitate to get in touch again.

best wishes
James Ellis-Jones
CEO Lynicon
________________________________

**Comment by dotnetshadow** [comment]
Good stuff, maybe you can update this ticket when things are rolling I will get a notification through here

**Comment by jamesej** [comment]
Hi there is now an ASP.Net Core version on https://github.com/jamesej/lyniconanc.  As yet it's just for .Net 4.5 but it will be adapted to run on .Net Core.  The functionality should be unchanged though, it will just be a matter of internal changes to the code plus switching a few third party dependencies.

**Comment by jamesej** [comment]
We've now updated the https://github.com/jamesej/lyniconanc library to be fully .net core compatible, it supports .Net Standard 1.6 and .Net 4.6.

**Comment by dotnetshadow** [comment]
Great work, I'll try and check this out hopefully I can use it in my existing website

**Comment by jamesej** [comment]
Thanks, brilliant.  I'm very keen to get feedback, and I'd be more than happy to help you if you run into any problems, so let me know how you get on.


best wishes


James


James Ellis-Jones

CEO Lynicon

________________________________
